### ISSUE TITLE
Database shouldn't be part of Dockerfile

### ISSUE THREAD

**Issue by rdrongow** [Agent59/umfrager#1]
States should be kept independently, so that the state won't be lost, if anything happens to a (generally disposable) container. An easy way to achieve this, is to define a mount point from your runtime env.

Let's say you use docker-compose and your runtime is a linux system. Put something like this in your docker-compose.yml:

```
version: '2.4'

services:
  umfrager:
    container_name: umfrager
    image: umfrager
    volumes:
      - /my/path/database/:/database
```

On your linux-system you can put the db-file in the folder `my/path/database`. You can remove it from the Dockerfile. Run it with `docker-compose up`
